package:
  name: iapetus
  version: "0.0.0"

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - openmmtools
    - yank
    - mdtraj
    - progressbar2

test:
  requires:
    - pytest
  imports:
    - iapetus

about:
  home: add_url_here
  license: MIT License
